import { readdirSync, existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = "public/images";
const found = [];

function walk(dir, prefix) {
  if (!existsSync(dir)) return;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) walk(join(dir, e.name), `${prefix}${e.name}/`);
    else if (/\.(webp|png|avif)$/i.test(e.name)) found.push(prefix + e.name);
  }
}
walk(ROOT, "");
found.sort();

mkdirSync("lib", { recursive: true });
writeFileSync(
  "lib/asset-manifest.ts",
  `// GENERATED by scripts/scan-assets.mjs. Do not edit by hand.\n` +
    `export const AVAILABLE = new Set<string>([\n` +
    found.map((f) => `  ${JSON.stringify(f)},`).join("\n") +
    `\n]);\n`
);
console.log(`asset manifest: ${found.length} file(s)`);
